version: "3.4"
x-restart-policy: &restart_policy
  restart: unless-stopped

services:

  # Databases
  database:
    <<: *restart_policy
    image: "postgres:12.2"
    environment:
      POSTGRES_DB: "{{ cookiecutter.project_name }}"
      POSTGRES_USER: "{{ cookiecutter.project_name }}"
      POSTGRES_PASSWORD: "{{ cookiecutter.project_name }}!"
    ports:
      - "5432:5432"
    volumes:
      - "{{ cookiecutter.project_name }}-database:/var/lib/postgresql/data"
    networks:
      - internal

  mongo:
    <<: *restart_policy
    image: "mongo:6.0.5"
    volumes:
      - "{{ cookiecutter.project_name }}-mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "{{ cookiecutter.project_name }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ cookiecutter.project_name }}!"
      MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    networks:
      - internal

  # Visualization of the databases
  mongo-express:
    <<: *restart_policy
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: "{{ cookiecutter.project_name }}"
      ME_CONFIG_BASICAUTH_PASSWORD: "{{ cookiecutter.project_name }}!"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: "{{ cookiecutter.project_name }}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "{{ cookiecutter.project_name }}!"
      ME_CONFIG_MONGODB_URL: mongodb://{{ cookiecutter.project_name }}:{{ cookiecutter.project_name }}!@mongo:27017/?authMechanism=DEFAULT
    depends_on:
      - mongo
    networks:
      - internal

  adminer:
    <<: *restart_policy
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - internal

  # Web
  web:
    <<: *restart_policy
    build:
      target: local
      context: {{ cookiecutter.project_name }}/
    working_dir: /home/ubuntu/webs/{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}
    command: ./bin/run.sh
    depends_on:
      - database
      - mongo
    ports:
      - "3031:3031"
      - "4444:4444"
      - "8000:8000"
    volumes:
      - ./{{ cookiecutter.project_name }}:/home/ubuntu/webs/{{ cookiecutter.project_name }}/{{ cookiecutter.project_name }}
    networks:
      - internal

volumes:
  {{ cookiecutter.project_name }}-database:
    external: true
  {{ cookiecutter.project_name }}-mongo:
    external: true
  {{ cookiecutter.project_name }}-redis:
    external: true

networks:
  internal:
    driver: bridge
